theme: jekyll-theme-hacker
navigation:
  - title: Home
    url: https://phantomreaperstudios.github.io/PRSSite/
  - title: Team Members
    url: https://phantomreaperstudios.github.io/PRSSite/Team%20Members/TeamMembers
